service: user-management-crud

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  stage: ${sls:stage, 'dev'}
  environment:
    USERS_TABLE: users-${sls:stage}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Query"
          Resource:
            - !GetAtt UsersTable.Arn

functions:
  getUser:
    handler: src/user-management-handler.getUser
    events:
      - http:
          path: /users/{id}
          method: get

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
